TARGET = kernel.elf
OBJS = boot/boot.o kernel/kernel.o kernel/graphics.o kernel/input.o

CC = x86_64-elf-gcc
LD = x86_64-elf-ld
CFLAGS = -ffreestanding -mno-red-zone -O2 -Wall -Wextra
LDFLAGS = -T boot/linker.ld -nostdlib

all: $(TARGET)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

%.o: %.s
	$(CC) -c $< -o $@

$(TARGET): $(OBJS)
	$(LD) $(LDFLAGS) $(OBJS) -o $@

iso:
	mkdir -p iso/boot/grub
	cp $(TARGET) iso/boot/
	cp iso/boot/grub/grub.cfg iso/boot/grub/grub.cfg
	grub-mkrescue -o nucaxOS.iso iso

run: all iso
	qemu-system-x86_64 -cdrom nucaxOS.iso

clean:
	rm -f $(OBJS) $(TARGET)
	rm -rf iso nucaxOS.iso
